Update to version 7.3.629, Fixes MER#168
Removed individual patches (because applying 629 separate patches would
have been slow and inconvenient) and created a tarball from the
latest upstream version from https://vim.googlecode.com/hg/ at:

changeset:   3741:9266cfe865c3
tag:         tip
user:        Bram Moolenaar <bram@vim.org>
date:        Wed Aug 08 18:01:05 2012 +0200
summary:     Added tag v7-3-629 for changeset 7de7ef01288d

Then run "make unixall" and renamed vim-7.3.tar.bz2 to vim-7.3.629.tar.bz2

Also Dutch lang files seemed to be added and causing this error:

error: Installed (but unpackaged) file(s) found:
   /usr/share/vim/vim73/lang/nl/LC_MESSAGES/vim.mo

which needed a line addition to the spec file.

Signed-off-by: Lauri Kaila <lauri.kaila@gmail.com>